# Generated by Django 4.2.1 on 2023-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('ref', models.IntegerField(blank=True, null=True)),
                ('oneway', models.CharField(blank=True, max_length=250, null=True)),
                ('maxspeed', models.IntegerField(blank=True, null=True)),
                ('layer', models.IntegerField(blank=True, null=True)),
                ('bridge', models.CharField(blank=True, max_length=250, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=250, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
